
#pragma once

enum EComponentType
{
    ECT_OBJECT2D,
    ECT_SPRITE2D,
    ECT_PROGRESS2D,
    ECT_TEXT2D,
    ECT_TILEMAP2D,
    ECT_CAMERA3D,
    ECT_OBJECT3D,
    ECT_STATICMODEL,
    ECT_RIGIDBODY2D,
    ECT_COLLISIONBOX2D,
    ECT_SOUNDLISTENER,
    ECT_SOUNDSOURCE,
    ECT_INPUT,
    ECT_UPDATE
};
